ghost:
  build: .
  command: '/bin/sh -c "cd /application && npm start "'
  ports:
    - '2368:2368'
  environment:
    - DOCKER_HOST=$DOCKER_HOST
  volumes:
    - 'themes:/application/content/themes'