ghost:
  image: thehumaneffort/ghost-template-editor:latest
  command: '/bin/sh -c "cd /application && npm start "'
  ports:
    - '2368:2368'
  environment:
    - DOCKER_HOST=$DOCKER_HOST
  volumes:
    - './data:/application/content/data'
    - './themes:/application/content/themes'